site_name: DBA Docs
site_url: http://ruslan-potomka.github.io/short-docs
site_author: Ruslan Potomka
site_description: Database Administrator's Brief Documentation
copyright: >
  © 2026 Ruslan —
  <a href="https://www.linkedin.com/in/ruslan-potomka" target="_blank" rel="noopener">
    LinkedIn
  </a>
extra:
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  language: ru
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
nav:
  - Главная: index.md